config/routes.rb
Zingatlas::Application.routes.draw do
  
  get "offers/index"
  get "offers/show"
  get "offers/new"
  get "offers/create"
  get "offers/edit"
  get "offers/update"
  get "offers/destroy"

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => { :registrations => 'registrations' }

  resources :authentications, :only => [:index, :create, :destroy]
  resources :itemrequests
  resources :travelinfos
  
  
  resources :offers
  
  resources :friendships
  
  
  get "pages/landing"
  match '/landing' => 'pages#landing'
  match '/friends' => 'pages#friends'
  match '/userlist' => 'pages#userlist'
  
  root :to => "pages#landing"
  
  resources :friendships
  

end

app/models/travelinfo.rb
class Travelinfo < ActiveRecord::Base
  attr_accessible :user_id, :uid, :origin, :destination, :departdate, :returndate, :willship
end

app/controllers/travelinfos_controller.rb
class TravelinfosController < ApplicationController
  def index
    @travelinfos = Travelinfo.all
  end

  def show
    @travelinfo = Travelinfo.find(params[:id])
  end

  def new
    @travelinfo = Travelinfo.new
  end

  def create
    @travelinfo = Travelinfo.new(params[:travelinfo])
    if @travelinfo.save
      redirect_to @travelinfo, :notice => "Successfully created travelinfo."
    else
      render :action => 'new'
    end
  end

  def edit
    @travelinfo = Travelinfo.find(params[:id])
  end

  def update
    @travelinfo = Travelinfo.find(params[:id])
    if @travelinfo.update_attributes(params[:travelinfo])
      redirect_to @travelinfo, :notice  => "Successfully updated travelinfo."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @travelinfo = Travelinfo.find(params[:id])
    @travelinfo.destroy
    redirect_to travelinfos_url, :notice => "Successfully destroyed travelinfo."
  end
end

app/helpers/travelinfos_helper.rb
module TravelinfosHelper
end

app/views/travelinfos/_form.html.erb
<%= form_for @travelinfo do |f| %>
  <%= f.error_messages %>
	<%= f.hidden_field :user_id, :value => current_user.id %>
     
  <p>
    <%= f.label :origin, "Departing from:" %><br />
    <%= f.text_field :origin %>
  </p>
  <p>
    <%= f.label :destination, "To:" %><br />
    <%= f.text_field :destination %>
  </p>
  <p>
    <%= f.label :departdate, "Departure date:" %><br />
    <%= f.date_select :departdate %>
  </p>
  <p>
    <%= f.label :returndate, "Return date:" %><br />
    <%= f.date_select :returndate %>
  </p>
  
  <p>
    Are you willing to get/bring something on this trip for friends? <br>
    <%= f.radio_button :willship, "Yes" %> Yes <br> 
	<%= f.radio_button :willship, "No" %> No <br>
	<%= f.radio_button :willship, "Not sure yet" %> Not sure yet <br>

    <%#= f.label :willship %><br />
    <%#= f.text_field :willship %>
  </p>
  
  <p><%= f.submit %></p>
<% end %>

app/views/travelinfos/edit.html.erb
<% title "Edit travel info" %>

<%= render 'form' %>

<p>
  <%#= link_to "Show", @travelinfo %> 
  <%= link_to "Back to my trip list", travelinfos_path %>
</p>

app/views/travelinfos/index.html.erb
<% user = User.all() %>

<% title "My trips" %>

<%= current_user.id %>

<table>
  <tr>
    
    <th>Departing from:</th>
    <th>To:</th>
    <th>Departure date</th>
    <th>Return date</th>
    <th>Willing to ship?</th>
  </tr>
  <% for travelinfo in @travelinfos %>
    <% if Integer(travelinfo.user_id) == current_user.id %>
	
    <tr>
        <td><%= travelinfo.origin %></td>
        <td><%= travelinfo.destination %></td>
        <td><%= travelinfo.departdate %></td>
        <td><%= travelinfo.returndate %></td>
        <td><%= travelinfo.willship %></td>
        <td><%= link_to "Edit", edit_travelinfo_path(travelinfo) %></td>
        <td><%= link_to "Delete", travelinfo, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
	<% end %>   <!-- end if statement to display current user info only -->
  <% end %>
</table>

<p><h2><%= link_to "Post new trip", new_travelinfo_path %></p></h2>


<h1> My friends' trips </h1>


<table>

  <tr>
    <th>Friend</th>
    <th>Departing from:</th>
    <th>To:</th>
    <th>Departure date</th>
    <th>Return date</th>
    <th>Willing to ship?</th>
  </tr>
  
  <% ufr = current_user.friendships %>
  <% ufr.each do |f| %> 
	
          <% for travelinfo in @travelinfos %> 
	        <% if Integer(travelinfo.user_id) == f.friend_id %>
				
              <tr>
              <td><%= f.friend_id %></td>  <!-- HOW TO LIST FRIEND NAME INSTEAD OF ID HERE??? -->
			  <td><%= travelinfo.origin %></td>
              <td><%= travelinfo.destination %></td>
              <td><%= travelinfo.departdate %></td>
              <td><%= travelinfo.returndate %></td>
              <td><%= travelinfo.willship %></td> 
              </tr>
	        <% end %>   <!-- end if statement to check for friends info -->
          <% end %>   <!-- end for loop through travelinfo -->
        
  
  <% end %> <!-- end f loop through user friendships -->
  
</table>  
  

app/views/travelinfos/new.html.erb
<% title "My new trip" %>

<%= render 'form' %>

<p><%= link_to "Back", travelinfos_path %></p>

app/views/travelinfos/show.html.erb
<% title "My travel plans" %>

<p>
  <strong>Departing from:</strong>
  <%= @travelinfo.origin %>
</p>
<p>
  <strong>Destination:</strong>
  <%= @travelinfo.destination %>
</p>
<p>
  <strong>Departure date:</strong>
  <%= @travelinfo.departdate %>
</p>
<p>
  <strong>Return date:</strong>
  <%= @travelinfo.returndate %>
</p>
<p>
  <strong>Willing to ship something for friends:</strong>
  <%= @travelinfo.willship %>
</p>

<p>
  <%= link_to "Edit", edit_travelinfo_path(@travelinfo) %> |
  <%= link_to "Delete", @travelinfo, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Back to my trip list", travelinfos_path %>
</p>