config/routes.rb
Zingatlas::Application.routes.draw do
  
  get "offers/index"
  get "offers/show"
  get "offers/new"
  get "offers/create"
  get "offers/edit"
  get "offers/update"
  get "offers/destroy"

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => { :registrations => 'registrations' }

  resources :authentications, :only => [:index, :create, :destroy]
  resources :itemrequests
  resources :travelinfos
  
  
  resources :offers
  
  resources :friendships
  
  
  get "pages/landing"
  match '/landing' => 'pages#landing'
  match '/friends' => 'pages#friends'
  match '/userlist' => 'pages#userlist'
  
  root :to => "pages#landing"
  
  resources :friendships
  

end

app/views/pages/friends.html.erb
<section id="auth">
<h1>Users and their friends</h1>

<% if auths = Authentication.find_all_by_provider('facebook') %>
      <% auths.each do |auth| %>
        <% friends = auth.find_friends %>
          <div class="user">
           <div class="id">User ID: <%= auth.user_id %> </div>
           <div class="name">User Name: <%= auth.name %> uid: <%= auth.uid %></div>
           <div class="email">User Email: <%= auth.email %> </div>

           <div class="friends">Friends: <%= friends["data"].length %> friends found
           <br>
           <% friends["data"].each do |f| %> 
            <%= f %>
            Name: <%= f["name"] %> uid: <%= f["id"] %><br>
           <% end %>
           </div> <br>
           <% if friends["paging"] %>   
              Url for more: <%= friends["paging"]["next"] %><br>
           <% end %>
          </div>
          <br><br>
       <% end %>
<% end %>

app/views/pages/landing.html.erb
<h1>Zingatlas logo</h1>


 
<!-- <TABLE BORDER="2" CELLPADDING="2" CELLSPACING="2" WIDTH="800"> -->
<!-- <TR> -->
<!-- <TD WIDTH="200">Column 1</TD> -->
<!-- <TD WIDTH="100">Column 2</TD> -->
<!-- </TR> -->
<!-- </TABLE> -->


<DIV style="
  position: absolute; 
  top:120px; left:150px; width:500px; height:25px">
  <strong>Friend-to-friend shipping network</strong><br>
  One good turn deserves another: use Zingatlas to send or receive items from abroad or help your friends move 
  their stuff around the world to avoid high shipping costs.
</DIV>


<DIV style="
  position: absolute; 
  top:120px; left:800px; width:200px; height:25px">
  
  <% if user_signed_in? %>
<!--    <%= link_to "Request an item", new_itemrequest_path %>     -->
	<%= link_to "View and Request items", itemrequests_path %>     
  <% else %>
    <%= link_to "Request an item", new_user_registration_path %>  
  <% end %>
</DIV>


<DIV style="
  position: absolute; 
  top:170px; left:800px; width:200px; height:25px">
  
  <% if user_signed_in? %>
    <%= link_to "View and post travel plans", travelinfos_path %>     
  <% else %>
    <%= link_to "Post travel plans", new_user_registration_path %>  
  <% end %>
  
</DIV>

  
</DIV>

<DIV style="
  position: absolute; 
  top:220px; left:200px; width:200px; height:25px">
<img src="http://placecupcak.es/640/480" alt="map placeholder" />
</DIV>

<br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br><br>
<br><br><br><br><br><br><br><br><br><br><br><br><br>
map placeholder

app/views/pages/offerdetails.html.erb
<% title "Offer Details" %>

<% user = User.all() %>
<% offer = Offer.all() %>

<% offer.each_with_index do |z, index | %>  
  <#% if z.itemrequest.id == itemrequest.id %>
	<% ux = User.find_by_id(z.user_id) %>
	<% junk = User.find_by_id(@array_userid) %>
	JUNK= <%= junk %> <br>
	
   	<%= z.id %>, <%= ux.email %>		<br>
  <#% end %>  <!-- check itemrequest_id == offer's itemrequest id -->
<% end %> <!-- z loop -->


<p><%= link_to "Back", itemrequests_path %> </p>

app/views/pages/userlist.html.erb
<% user = User.all() %>

<% cuf = current_user.friendships %>

<!--These functions are no longer defined in friendships_helper.rb -->
<!-- They re defined in user.rb and initialized in pages_controller.rb -->
<%# pf = pending_forward %> 
<%# pi = pending_inverse %> 
<%# myf = my_friendlist %>


<h1>Zingatlas users:</h1>
<%# here we implement the search form as in Railscast %>
<%= form_tag userlist_path, :method => 'get' do %>
  <p>
    <%= text_field_tag :search, params[:search] %>
    <%= submit_tag "Search", :name => nil %>
  </p>
<% end %>

<%# uu is replaced by @unconnected_users initialized in the controller pages_controller.rb %>
<% @unconnected_users.each_with_index do |r, index| %>
  <strong><%= r.email %> </strong>
  <%= link_to "Add Friend", friendships_path(:friend_id => r.id), :method => :post %> <br>
<% end %>

<br>


<h2>Friend requests sent to:</h2>

<% if @pending_forward_users.count > 0 %>  <!--current user has sent friend requests -->  
      
  <% @pending_forward_users.each do |pendingforward_output| %>
    <strong><%= pendingforward_output[0].email %> </strong> 
    (<%= link_to "remove", pendingforward_output[1] , :method => :delete %>) <br> 
  <% end %>
  <% else %>
    No outgoing friend requests. <br>	
<% end %>  <!--end @pending_forward_users.count if statement -->

 
<h2>Incoming friend requests:</h2>  

<% if @pending_inverse_users.count > 0 %> <!-- there are incoming unconfirmed and/or confirmed friend requests -->
  <% @pending_inverse_users.each do |pendinginv_output| %>
    <strong><%= pendinginv_output[0] %></strong> 
	<%= link_to "Accept", pendinginv_output[1], :method => :put %>,
    <%= link_to "Deny", pendinginv_output[1], :method => :delete %>	<br>
  <% end %>

<% else %>
  No incoming friend requests. <br>	
  
<% end %>


<h2>My Friends:</h2>  

<% if @my_friendlist_users.count > 0 %>
  <% @my_friendlist_users.each do |myfriends_output| %>
    <strong><%= myfriends_output[0].email %></strong> 
      (<%= link_to "remove", myfriends_output[1], :method => :delete %>)	<br>
  <% end %>
<% else %>
  No friends.
<% end %>

app/views/pages/userlist_OLD.html.erb
<% user = User.all() %>

<% pf = pending_forward %>
<% pfindex = testjunk %>
<% pi = pending_inverse %> 

<h2>Friend requests sent to:</h2>

<% if pf.count > 0 %>  <!--current user has sent friend requests -->        
  <% pf.each_with_index do |t, index| %>
   <strong><%= t %> </strong>
   (<%= link_to "remove", pfindex[index] , :method => :delete %>) <br>
  <% end %>
  <% else %>
    No incoming friend requests. <br>	
<% end %>  <!--end pf.count if statement -->
  
<h2>Incoming friend requests:</h2>  
<% if pi.count > 1 %>  <!--current user has incoming friend requests -->
  <% pi.each do |r| %>
   <strong><%= r.email %> </strong> <%= r.id %>
   <%= link_to "Accept", friendships_path(:friend_id => r.id), :method => :post %> <br>
   <br>
  <% end %>
<% end %>



<br>

<h1>Make a friend request to a Zingatlas user:</h1>

<% user.each do |f| %> 
  <div class="user">
	<% if f.email != current_user.email %>
      <strong><%= f.email %></strong> 
	  <%= link_to "Add Friend", friendships_path(:friend_id => f.id), :method => :post %> <br>
	<% end %>
    <div class="clear"></div>
  </div>	
<% end %> 

<h2>Friend requests sent to:</h2>

<% test = pending_forward %>
<% testj = testjunk %>
<% test.each_with_index do |t, index| %>
   <strong><%= t %> </strong>
   (<%= link_to "remove", testj[index] , :method => :delete %>) <br>
<% end %>


</br>

<br>OLD WAY: <br>  
<% ufr = current_user.friendships %>
<% ufr.each do |f| %> 
  <li>
  <% ux = User.find_by_id(f.friend_id) %>
    <%# user.each do |ux| %> <!-- don't need this inner loop!! use find_by fn above!!!!!! -->
	  <% if ux.id == f.friend_id %>   
	    <strong><%= ux.email %></strong> 
      <% end %>
    <%# end %>
    (<%= link_to "remove", f, :method => :delete %>) <%= f %>
  </li> 
<% end %> 
 
<h1>Incoming friend requests:</h1>

<% rlist = pending_inverse %> <br>
<% rlist.each do |r| %>
   <strong><%= r.email %> </strong> <%= r.id %>
   <%= link_to "Accept", friendships_path(:friend_id => r.id), :method => :post %> <br>
   
   
   <br>
<% end %>

<br>

<br> OLD WAY:<br>
<% uinf = current_user.inverse_friends %>  
 <ul>
  <% uinf.each do |f| %> 
	<li>
	<strong><%= f.email %></strong> 
    <%= link_to "Accept", friendships_path(:friend_id => f.id), :method => :post %> <br>
	</li>
	<% end %>
</ul>
 
<h1>My friends:</h1>

<% uinf = current_user.inverse_friends %> 
<% ufr = current_user.friendships %>

 <ul>
  <% uinf.each do |f| %>  
    
	<% current_user.friendships.each do |ux| %> 
<%#= f.email %>	<%#= f.id %> <br>
<%#= ux.user_id %> <%#= ux.friend_id %>

	  <% if ux.friend_id == f.id %>   
	    <li>
	      <strong><%= f.email %></strong> (<%= link_to "remove", ux, :method => :delete %>)
   	    </li>
	  <% end %>   <!-- end if statement -->	  
    <% end %>   <!-- end ux loop -->	
  <% end %>   <!-- end f loop -->
</ul>
 

app/views/pages/userlist_tmp.html.erb
<% user = User.all() %>

<% cuf = current_user.friendships %>
<%# cuif = current_user.inverse_friends %>

<!--Functions defined in friendships_helper.rb -->
<% uu = unconnected_users %>
<% uufriendid = uu_fid %> <!--TEMPORARY FN UNTIL I GET HELP!-->
<% pf = pending_forward %>
<% pfindex = testjunk %>     <!--TEMPORARY FN UNTIL I GET HELP!-->
<% pi = pending_inverse %> 
<% myf = my_friendlist %>
<% myfindex = my_friendlist_index %> <!--TEMPORARY FN UNTIL I GET HELP!-->

<h1>Zingatlas users:</h1>
<% uu.each_with_index do |r, index| %>
  <strong><%= r %> </strong> <%= uufriendid[index] %>
  <%= link_to "Add Friend", friendships_path(:friend_id => uufriendid[index]), :method => :post %> <br>
<% end %>

<br>

<h2>Friend requests sent to:</h2>

<% if pf.count > 0 %>  <!--current user has sent friend requests -->        
  <% pf.each_with_index do |t, index| %>
   <strong><%= t %> </strong> <%= pfindex[index] %>
   (<%= link_to "remove", pfindex[index] , :method => :delete %>) <br>
  <% end %>
  <% else %>
    No outgoing friend requests. <br>	
<% end %>  <!--end pf.count if statement -->
  
<h2>Incoming friend requests:</h2>  
test<br>

<% requester = current_user.inverse_friendships.find(:all) %>
<%= requester %><br>

<% if pi.count > 1 %>
      <% pi.each do |r| %>
       <!-- read pending col -->
	    <% user.each_with_index do |f,index| %>
	      <% if index == r.user_id - 1 %>
            <% pending = f.friendships[0].pending %>
			<%= pending %>
			
	      <% end %>
        <% end %>
      <% end %>
    <% end %>

end test<br><br>

<% if pi.count > 0 %>  <!--current user has incoming friend requests -->
  <% pi.each do |r| %>
   <% ux = User.find_by_id(r.user_id) %> <strong><%= ux.email %></strong> 
   <%#= link_to "Accept", friendships_path(:user_id => r.id), :method => :put %>
   <%= link_to "Accept", r, :method => :put %> <br>
  <% end %>
  <% else %>
    No incoming friend requests. <br>	
<% end %>

<br>try:<br>
size:<%= cuf.size %><br>
<%#= current_user.friendships[0].pending %>,
<%#= current_user.friendships[1].pending %>,
<%#= current_user.friendships[2].pending %><br>

<%# for i in 0..@cuf.size-1 %>
  <%# if current_user.friendships[i].pending != 2 %>
    <%# tmp = current_user.friendships[i].friend_id %><br>
	<%# ux = User.find_by_id(tmp) %>
	<%#= ux.email %><br>
  <%# end %>
<%# end %>  
 
 <br>
  


<br>

 
<h1>My friends:</h1>
<% if myf.count > 0 %>  <!--current user has accepted incoming friend requests -->
  <% myf.each_with_index do |r, index| %>
    <strong><%= r %> </strong> <%= myfindex[index] %>
     (<%#= link_to "remove", myf[index] , :method => :delete %>) <br><br>
  <% end %>
<% else %>
    No friends currently. <br>	  
<% end %>




<!-- OLD 
<br><br>
<h2>Friends</h2>
current_user: <%= current_user %>, <%= current_user.id %>, # requests: <%= cuf.size %><br>
-->





<!-- OLD 
<% user.find([:id]) %><br>
user.last: <%= user.last %><br>
user.second.friendships[0].pending: <%= user.second.friendships[0].pending %><br>
user.third.friendships[0].friend_id: <%= user.third.friendships[0].friend_id %><br>

<br><br>

<% user.each do |f| %>
  <% ux = User.find_by_id(f.friendships) %>
  <%= ux %> <br> f.friendships:<br>
  <%= f.friendships %> <br>
<% end %>
-->