config/routes.rb
Zingatlas::Application.routes.draw do
  
  get "offers/index"
  get "offers/show"
  get "offers/new"
  get "offers/create"
  get "offers/edit"
  get "offers/update"
  get "offers/destroy"

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => { :registrations => 'registrations' }

  resources :authentications, :only => [:index, :create, :destroy]
  resources :itemrequests
  resources :travelinfos
  
  
  resources :offers
  
  resources :friendships
  
  
  get "pages/landing"
  match '/landing' => 'pages#landing'
  match '/friends' => 'pages#friends'
  match '/userlist' => 'pages#userlist'
  
  root :to => "pages#landing"
  
  resources :friendships
  

end

app/models/itemrequest.rb
class Itemrequest < ActiveRecord::Base
  attr_accessible :user_id, :uid, :getorsend, :name, :destination, :origin, :description, :weight, :completiondate
end

app/controllers/itemrequests_controller.rb
class ItemrequestsController < ApplicationController
  def index
    @itemrequests = Itemrequest.all     #.find(params[:user_id]) 
	@my_friendlist_users = current_user.my_friendlist
  end

  def show
    @itemrequest = Itemrequest.find(params[:id])
  end
  
  def new
    @itemrequest = Itemrequest.new
  end
  
  def create
	logger.debug "ITEMREQUEST: CREATE"
    @itemrequest = Itemrequest.new(params[:itemrequest])
    if @itemrequest.save
      redirect_to @itemrequest, :notice => "Successfully created itemrequest."
    else
      render :action => 'new'
    end
  end

  def edit
    @itemrequest = Itemrequest.find(params[:id])
	#CN edits because edits are not saved!!!
	#@itemrequest.save
  end

  def update
    #CN edits. Update now handles offers (via act param) as well as updates to item info	
	if(params[:act] !=nil) #If false, update relates to item info so skip to line 89
		fid = Integer(params[:act])
		logger.debug "READING OFFER PARAMS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
		@user = User.all()
		@itemrequest = Itemrequest.find_by_id(params[:id])
		if(fid == 1)
			logger.debug "ADD OFFER!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
			@itemrequest.offeredby = current_user.id 
			#@itemrequest.update_attributes(:offeredby => 3) #this does not do anything!!!
			#@itemrequest.update_attributes(:weight => 3) #this works though
		else #(fid == 0)
			logger.debug "REMOVE OFFER!!!!!!!!!!!!!!!!!!!!!!!!!"
			@itemrequest.offeredby = nil
		end
		
		if @itemrequest.save
			redirect_to itemrequests_path
			flash[:notice] = "Offer submitted."
		else
			flash[:notice] = "Unable to submit offer."
			redirect_to root_url
		end
	else #update itemrequest info as before
	   logger.debug "AS BEFORE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
       @itemrequest = Itemrequest.find(params[:id])
       if @itemrequest.update_attributes(params[:itemrequest])
        redirect_to @itemrequest, :notice  => "Successfully updated itemrequest."
		logger.debug "UPDATE ITEM INFOS!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
      else
	    logger.debug "RENDERING EDIT!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
        render :action => 'edit'
      end
	end
	  
	  
	  
  end
  
  def offer
	#CN edits
	if(params[:act] !=nil)
		fid = Integer(params[:act])
	end
	logger.debug "update offer by traveller"
	@user = User.all()
	@itemrequest = Itemrequest.find_by_id(params[:id])
	if(fid == 1)
		logger.debug "add offer"
		@itemrequest.offeredby = current_user.id 
		#@itemrequest.update_attributes(:offeredby => 3) #this does not do anything!!!
		#@itemrequest.update_attributes(:weight => 3) #this works though
	elsif(fid == 0)
		logger.debug "remove offer"
		@itemrequest.offeredby = Integer(nil)
	else
		logger.debug "no item"
	end	

	if @itemrequest.save
		#flash[:notice] = "Added friend."
		#redirect_to root_url
		redirect_to itemrequests_path
		flash[:notice] = "Offer submitted."
	else
		flash[:notice] = "Unable to submit offer."
		redirect_to root_url
	end

	#try this
	#@itemrequest = Itemrequest.find(params[:id])
    #if @itemrequest.update_attributes(:offeredby => 3)
    #  redirect_to itemrequests_path, :notice  => "Offer submitted."
    #else
    #  #render :action => 'edit'
	#  flash[:notice] = "Unable to submit offer."
    #end
	
	
  end

  def destroy
    @itemrequest = Itemrequest.find(params[:id])
    @itemrequest.destroy
    redirect_to itemrequests_url, :notice => "Successfully destroyed itemrequest."
  end
end

app/helpers/itemrequests_helper.rb
module ItemrequestsHelper
end

app/views/itemrequests/_form.html.erb
<% user = User.all() %>

<%= form_for @itemrequest do |f| %>
  <%= f.error_messages %>
  <!--<p>-->
	<%= f.hidden_field :user_id, :value => current_user.id %>
    <%#= f.label :current_user.email %><br />
    <%#= f.number_field :user_id %>
  <!--</p>-->
  <!--<p>-->
    <%#= f.label :uid %><br />
    <%#= f.text_field :uid %>
  <!--</p>-->
  <!--<p>-->
     <%= f.radio_button :getorsend, "Get" %> Get an item 
     <%= f.radio_button :getorsend, "Send" %>Send an item 
  <%#  <%= f.label :getorsend %>
  <%#  <%= f.text_field :getorsend %>

  <!--</p>-->
  <p>
    <%= f.label :name, "Item" %><br />
    <%= f.text_field :name %>
  </p>
  <p>
    <%= f.label :destination, "To:" %><br />
    <%= f.text_field :destination %>
  </p>
  <p>
    <%= f.label :origin, "From:" %><br />
    <%= f.text_field :origin %>
  </p>
  <p>
    <%= f.label :description %><br />
    <%= f.text_area :description %>
  </p>
  <p>
    <%= f.label :weight, "Weight (kg)" %><br />
    <%= f.text_field :weight %>
  </p>
  <p>
    <%= f.label :completiondate, "Need by:" %><br />
    <%= f.date_select :completiondate %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/itemrequests/edit.html.erb
<% title "Edit Itemrequest" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @itemrequest %> |
  <%= link_to "View All", itemrequests_path %>
</p>

app/views/itemrequests/index.html.erb
<% user = User.all() %>
<% offer = Offer.all() %>

<% title "My item requests" %>


<table>

  <tr>
    <!--<th>User</th>-->
    <!--<th>Uid</th>-->
    <th>Delivery</th>
    <th>Item</th>
    <th>To</th>
    <th>From</th>
    <th>Description</th>
    <th>Weight</th>
    <th>Need by</th>
	<th></th>
	<th></th>
	<th>Offers</th>
  </tr>
  
  <% for itemrequest in @itemrequests %> 
    <% if itemrequest.user_id == current_user.id %>
	 	
      <tr>
        <!--<td><%= itemrequest.user_id %></td>-->
        <!--<td><%= itemrequest.uid %></td>-->
        <td><%= itemrequest.getorsend %></td>
        <td><%= itemrequest.name %></td>
        <td><%= itemrequest.destination %></td>
        <td><%= itemrequest.origin %></td>
        <td><%= itemrequest.description %></td>
        <td><%= itemrequest.weight %></td>
        <td><%= itemrequest.completiondate.strftime("%a %d %B %Y") %></td>
		<td><%= link_to "Edit", edit_itemrequest_path(itemrequest) %></td>
		<td><%= link_to "Delete", itemrequest, :confirm => 'Are you sure?', :method => :delete %></td>
		
		
		<% flag_offers = 0 %>
		<% array_userid=[] %>
		<% count = 0 %>
		<% offerer_id =0 %> <!-- initialize -->
		<!-- Cycle through offers table to see if there are any offers -->
		<% if offer.count > 0 %>
		  <% offer.each_with_index do |z, index | %>  
		  <% if z.itemrequest.id == itemrequest.id %>
			<% ux = User.find_by_id(z.user_id) %>
			<% flag_offers = 1 %>
			<% array_userid[count] = z.user_id %>
			<% count += 1 %> 
			  
			  
			
		  <% end %>  <!-- check itemrequest_id == offer's itemrequest id -->
         <% end %> <!-- z loop -->
		<% end %> <!-- offer.count check -->	
		
		
		<% if flag_offers == 1 %>		      
   		      <td>You have offers! <%= link_to "Details", offers_path(:itemrequest=> itemrequest.id) %> </td>
		<% else %>  
		  <td>No takers yet. </td>
		<% end %>  
		


      </tr>
	<% end %>   <!-- end if statement to display current user info only -->
  <% end %>   <!-- end for loop through itemrequest -->
  
</table>

<p>
<!-- <%= link_to "Request a new item", new_itemrequest_path %> | <%= link_to "Home", root_path %> | -->

<% if offer.count == 0 %>
  <h2> <%= link_to "Request a new item", new_itemrequest_path %> </h2>
<% else %>
  <h2> <%= link_to "Request another item", new_itemrequest_path %> </h2>
<% end %>  
</p>

<%# myf = my_friendlist %> <!-- fn defined in user.rb and initialized in pages_controller.rb -->

<br>
<h1> My friends' item requests </h1>

<%= link_to "Offers I have made", offers_path %>
    
  <% if @my_friendlist_users.count > 0 %>
    <table>
    <tr>
      <th>Friend</th>
      <th>Delivery</th>
      <th>Item</th>
      <th>To</th>
      <th>From</th>
      <th>Description</th>
      <th>Weight</th>
      <th>Need by</th>
	  <th></th>
    </tr>

    <% @my_friendlist_users.each do |f| %> 
	  	  
        <% for itemrequest in @itemrequests %> 
          <% if itemrequest.user_id == f[0].id %>
		  						
              
            <tr>
              <td><%= f[0].email %></td>  
			  <td><%= itemrequest.getorsend %></td>
              <td><%= itemrequest.name %></td>
              <td><%= itemrequest.destination %></td>
              <td><%= itemrequest.origin %></td>
              <td><%= itemrequest.description %></td>
              <td><%= itemrequest.weight %></td>
              <td><%= itemrequest.completiondate.strftime("%a %d %B %Y") %></td> 
			  
			  
			  <% flag_madeoffer = 0 %>
			  <% offer_row = 0 %>
			  <!-- Cycle through offers table to see if current_user has already made an offer -->
			  <% if offer.count > 0 %>
			    <% offer.each do |z| %>  
			      <% if z.itemrequest.id == itemrequest.id %>
				    <% if z.user_id == current_user.id %>
                      <% flag_madeoffer = 1 %>
					  <% offer_row = z.id %>
				    <% end %>	
				  <% end %>  <!-- check itemrequest_id == offer's itemrequest id -->
                <% end %> <!-- z loop -->
			  <% end %> <!-- offer.count check -->	
			  
			
			  
			  
			  <% if flag_madeoffer == 1 %>
			  
			    
   		        <td>I have offered do this </td>
				<!-- link_to "Delete offer", itemrequest_path(:id=>itemrequest, :act => 0), :method=>:put -->
				
				  <% offer.each do |z| %>  
				    <% if (z.itemrequest.id == itemrequest.id && z.user_id == current_user.id ) %>				      
					  <td><%= link_to "Delete offer", offer_path(:id=>offer_row), :method=>:delete %>	</td>					    				      
				    <% end %>  <!-- check itemrequest_id == offer's itemrequest id -->
                  <% end %> <!-- z loop -->
				
				
				
				
				<br>
				
				
		      <% elsif flag_madeoffer == 0 %>  
		        <!-- link_to "I can do this", itemrequest_path(:id=>itemrequest, :act=>1), :method => :put -->
				
				
				<td><%= link_to "I can do this", new_offer_path(:id=>itemrequest) %> </td><br>
				
		      <% end %>
		
			  
            </tr>
	      <% end %>   <!-- end if statement to check for friends info -->
        <% end %>   <!-- end for loop through itemrequest -->
        
		  		
    <% end %> <!-- end f loop through user friendships -->
	</table>
	
  <% else %>	
  Your friends have no requests.
  
  <% end %> <!-- end @my_friendlist_users.count check -->	
  
  
  

app/views/itemrequests/new.html.erb
<% title "New Itemrequest" %>

<%= render 'form' %>

<p><%= link_to "Back", itemrequests_path %></p>

app/views/itemrequests/show.html.erb
<% title "Item request" %>

<!--<p>-->
<!--  <strong>User:</strong>-->
<!--  <%= @itemrequest.user_id %>-->
<!--</p>-->
<!--<p>-->
<!--  <strong>Uid:</strong>-->
<!--  <%= @itemrequest.uid %>-->
<!--</p>-->
<p>
  <strong>Getorsend:</strong>
  <%= @itemrequest.getorsend %>
</p>
<p>
  <strong>Name:</strong>
  <%= @itemrequest.name %>
</p>
<p>
  <strong>Destination:</strong>
  <%= @itemrequest.destination %>
</p>
<p>
  <strong>Origin:</strong>
  <%= @itemrequest.origin %>
</p>
<p>
  <strong>Description:</strong>
  <%= @itemrequest.description %>
</p>
<p>
  <strong>Weight:</strong>
  <%= @itemrequest.weight %>
</p>
<p>
  <strong>Completiondate:</strong>
  <%= @itemrequest.completiondate %>
</p>

<p>
  <%= link_to "Edit", edit_itemrequest_path(@itemrequest) %> |
  <%= link_to "Delete", @itemrequest, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "Back to Item Request list", itemrequests_path %>
</p>