config/routes.rb
Zingatlas::Application.routes.draw do
  
  get "offers/index"
  get "offers/show"
  get "offers/new"
  get "offers/create"
  get "offers/edit"
  get "offers/update"
  get "offers/destroy"

  match '/auth/:provider/callback' => 'authentications#create'
  devise_for :users, :controllers => { :registrations => 'registrations' }

  resources :authentications, :only => [:index, :create, :destroy]
  resources :itemrequests
  resources :travelinfos
  
  
  resources :offers
  
  resources :friendships
  
  
  get "pages/landing"
  match '/landing' => 'pages#landing'
  match '/friends' => 'pages#friends'
  match '/userlist' => 'pages#userlist'
  
  root :to => "pages#landing"
  
  resources :friendships
  

end

app/models/offer.rb
class Offer < ActiveRecord::Base
  attr_accessible :itemrequest_id, :user_id, :cando_date
  belongs_to :itemrequest
end

app/controllers/offers_controller.rb
class OffersController < ApplicationController
  def index
    if params[:itemrequest].nil?
      @offers = Offer.where(:user_id => current_user.id) #selects offers made to current user
	  @offersmade=1
	else
	  @offers = Offer.where(:itemrequest_id => params[:itemrequest]) #selects current user's offers to friends
	  @offersmade=0
    end	
  end

  def show
     @offer = Offer.find(params[:id])
  end

  def new
    @offer = Offer.new
	logger.debug "IN NEW!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
		
	@itemrequest = Itemrequest.find_by_id(params[:id])
	@offer.itemrequest_id = @itemrequest.id 
	
	@user = User.all()
	@offer.user_id = current_user.id 

   if @offer.save
      #redirect_to @offer, :notice => "Successfully created offer."
	  logger.debug "ADDED ITEMREQUEST ID!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    else
      render :action => 'new'
    end

	
  end

  def create
    @offer = Offer.new(params[:offer])
	@itemrequest = Itemrequest.find_by_id(params[:id])
	
	@user = User.all()
	#@offer = Offer.find_by_id(params[:id])
	logger.debug "IN CREATE!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
	@offer.user_id = current_user.id 
	
	
    if @offer.save
      redirect_to @offer, :notice => "Successfully created offer."
	  logger.debug "ADDED USER ID!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!!"
    else
      render :action => 'new'
    end
	
	
  end

  def edit
    @offer = Offer.find(params[:id])
  end

  def update
    @offer = Offer.find(params[:id])
    if @offer.update_attributes(params[:offer])
      redirect_to @offer, :notice  => "Successfully updated offer."
    else
      render :action => 'edit'
    end
  end

  def destroy
    @offer = Offer.find(params[:id])
    @offer.destroy
    redirect_to itemrequests_path, :notice => "Successfully destroyed offer."
  end
end

app/helpers/offers_helper.rb
module OffersHelper
end

app/views/offers/_form.html.erb
<%= form_for @offer do |f| %>
  <%= f.error_messages %>
  
    <%#= f.label :itemrequest_id %><br />
    <%#= f.number_field :itemrequest_id %>
  
    <%#= f.label :user_id %><br />
    <%#= f.number_field :user_id %>

  <p>
    <%= f.label :cando_date, "I can get/deliver by:"  %><br />
    <%= f.date_select :cando_date %>
  </p>
  <p><%= f.submit %></p>
<% end %>

app/views/offers/edit.html.erb
<% title "Edit Offer" %>

<%= render 'form' %>

<p>
  <%= link_to "Show", @offer %> |
  <%= link_to "View All", offers_path %>
</p>

app/views/offers/index.html.erb
<% user = User.all() %>
<% itemrequest = Itemrequest.all() %>

 <pre><% if  @offersmade  == 0 %></pre>
   hello
 <% end %>




<!-- RENDER THIS VIEW IF SHOWING OFFERS MADE *TO* CURRENT USER -->
 <pre><% if  @offersmade  == 0 %></pre>

  <% loopflag=0 %>
  <table>
    <tr>
    
	  <th>Name</th>
      <th>Can do by: </th>
    </tr>
    <% for offer in @offers %>
      <kkk % if offer.user_id == current_user.id %>
	  <% if loopflag==0 %>
	    <h1>Offers for your <%= Itemrequest.find_by_id(offer.itemrequest_id).name %></h1>
	    <h3><%= Itemrequest.find_by_id(offer.itemrequest_id).getorsend %> from 
	    <%= Itemrequest.find_by_id(offer.itemrequest_id).origin %> to 
	    <%= Itemrequest.find_by_id(offer.itemrequest_id).destination %> by 
	    <%= Itemrequest.find_by_id(offer.itemrequest_id).completiondate.strftime("%a %d %B %Y") %></h3><br>
	    <% loopflag = 1 %>
	  <% end %>  
	
      <tr>
        
		<td><%= User.find_by_id(offer.user_id).email %></td>
        <td><%= offer.cando_date.strftime("%a %d %B %Y") %></td>
        <td><%= link_to "Show", offer %></td>
        <td><%= link_to "Edit", edit_offer_path(offer) %></td>
        <td><%= link_to "Destroy", offer, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
	<kkk% end %>  
    <% end %>
  </table>

<% else %>  
<!-- RENDER THIS VIEW IF SHOWING OFFERS MADE *BY* CURRENT USER -->
  <h1>Offers you have made to your friends </h1>
  
  <table>
    <tr>
    
	  <th>Friend</th>
	  <th>Item	</th>
      <th>Can do by: </th>
    </tr>
    <% for offer in @offers %>
      
	   
	
      <tr>
        <% junk= offer.itemrequest_id %>
		<% junk2= Itemrequest.find_by_id(junk).user_id %>
		<% junk3= User.find_by_id(junk2).email %> 
		<% efriend= User.find_by_id(Itemrequest.find_by_id(offer.itemrequest_id).user_id).email %> 

		<td><%= efriend %></td>
		<td><%= Itemrequest.find_by_id(offer.itemrequest_id).name %></td>
        <td><%= offer.cando_date.strftime("%a %d %B %Y") %></td>
        <td><%= link_to "Show", offer %></td>
        <td><%= link_to "Edit", edit_offer_path(offer) %></td>
        <td><%= link_to "Destroy", offer, :confirm => 'Are you sure?', :method => :delete %></td>
      </tr>
	
    <% end %>
  </table>

<% end %> <!-- if check for offersmade param -->

<%#= link_to "New Offer", new_offer_path %>
<p><%= link_to "Back to item requests", itemrequests_path %></p>

app/views/offers/new.html.erb
<% title "New Offer" %>

<!-- user = User.all() -->
<!-- itemrequest = Itemrequest.find_by_id(params[:id]) -->
<!-- itemrequest = Itemrequest.all() -->
<!-- itemrequest[6].id --> 


<%= render 'form' %>

<p><%= link_to "Back to List", offers_path %></p>

app/views/offers/show.html.erb
<% title "Offer show" %>

<p>
  <strong>I can get/send by:</strong>
  <%= @offer.cando_date %>
</p>

<p>
  <%= link_to "Edit", edit_offer_path(@offer) %> |
  <%= link_to "Delete", @offer, :confirm => 'Are you sure?', :method => :delete %> |
  <%= link_to "View All My Offers", offers_path %> |
  <%= link_to "Back to item requests", itemrequests_path %>     
</p>